#!/usr/bin/env python3
"""Convert assets/Wiimote *.png into firmware/imu_demo/include/wiimote_textures.h (RGB565)."""

from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
REPO_ROOT = PROJECT_DIR.parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
OUT_PATH = PROJECT_DIR / "include" / "wiimote_textures.h"

TEXTURES = (
    ("Front", "Wiimote Front.png", "kTexFront", "kTexFrontWidth", "kTexFrontHeight"),
    ("Back", "Wiimote Back.png", "kTexBack", "kTexBackWidth", "kTexBackHeight"),
    ("Top", "Wiimote Top.png", "kTexTop", "kTexTopWidth", "kTexTopHeight"),
    ("Bottom", "Wiimote Bottom.png", "kTexBottom", "kTexBottomWidth", "kTexBottomHeight"),
)


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa = abs(p - a)
    pb = abs(p - b)
    pc = abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def decode_png(path: Path) -> tuple[int, int, list[tuple[int, int, int]]]:
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path} is not a PNG file")

    pos = 8
    width = height = 0
    bit_depth = color_type = 0
    idat = bytearray()

    while pos < len(data):
        if pos + 8 > len(data):
            break
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        chunk_type = data[pos + 4 : pos + 8]
        chunk = data[pos + 8 : pos + 8 + length]
        pos += 12 + length

        if chunk_type == b"IHDR":
            width, height, bit_depth, color_type, _, _, _ = struct.unpack(">IIBBBBB", chunk)
        elif chunk_type == b"IDAT":
            idat.extend(chunk)
        elif chunk_type == b"IEND":
            break

    if color_type != 2 or bit_depth != 8:
        raise ValueError(f"{path}: expected 8-bit RGB PNG")

    raw = zlib.decompress(bytes(idat))
    stride = width * 3
    prev_row = bytearray(width * 3)
    pixels: list[tuple[int, int, int]] = []

    offset = 0
    for _ in range(height):
        filter_type = raw[offset]
        offset += 1
        row = bytearray(raw[offset : offset + stride])
        offset += stride

        if filter_type == 0:
            pass
        elif filter_type == 1:
            for i in range(stride):
                left = row[i - 3] if i >= 3 else 0
                row[i] = (row[i] + left) & 0xFF
        elif filter_type == 2:
            for i in range(stride):
                row[i] = (row[i] + prev_row[i]) & 0xFF
        elif filter_type == 3:
            for i in range(stride):
                left = row[i - 3] if i >= 3 else 0
                up = prev_row[i]
                row[i] = (row[i] + ((left + up) // 2)) & 0xFF
        elif filter_type == 4:
            for i in range(stride):
                left = row[i - 3] if i >= 3 else 0
                up = prev_row[i]
                up_left = prev_row[i - 3] if i >= 3 else 0
                row[i] = (row[i] + paeth(left, up, up_left)) & 0xFF
        else:
            raise ValueError(f"{path}: unsupported PNG filter {filter_type}")

        for x in range(width):
            i = x * 3
            pixels.append((row[i], row[i + 1], row[i + 2]))
        prev_row = row

    return width, height, pixels


def try_pillow_decode(path: Path) -> tuple[int, int, list[tuple[int, int, int]]] | None:
    try:
        from PIL import Image
    except ImportError:
        return None

    img = Image.open(path).convert("RGB")
    width, height = img.size
    pixels = list(img.getdata())
    return width, height, pixels


def load_png(path: Path) -> tuple[int, int, list[tuple[int, int, int]]]:
    pillow = try_pillow_decode(path)
    if pillow is not None:
        return pillow
    return decode_png(path)


def main() -> int:
    lines: list[str] = [
        "#pragma once",
        "",
        "// Auto-generated by firmware/imu_demo/scripts/embed_textures.py",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        "enum class WiimoteFaceTex : uint8_t {",
        "  None = 0,",
        "  Front,",
        "  Back,",
        "  Top,",
        "  Bottom,",
        "};",
        "",
        "struct WiimoteTexture {",
        "  const uint16_t* data;",
        "  uint8_t width;",
        "  uint8_t height;",
        "};",
        "",
    ]

    for _enum_name, filename, symbol, width_sym, height_sym in TEXTURES:
        path = ASSETS_DIR / filename
        if not path.exists():
            print(f"Missing texture: {path}", file=sys.stderr)
            return 1

        width, height, rgb_pixels = load_png(path)
        rgb565 = [rgb888_to_rgb565(r, g, b) for r, g, b in rgb_pixels]

        lines.append(f"constexpr uint8_t {width_sym} = {width};")
        lines.append(f"constexpr uint8_t {height_sym} = {height};")
        lines.append(f"const uint16_t {symbol}[{len(rgb565)}] PROGMEM = {{")
        row = "  "
        for i, value in enumerate(rgb565):
            row += f"0x{value:04X},"
            if (i + 1) % 12 == 0:
                lines.append(row)
                row = "  "
        if row.strip():
            lines.append(row.rstrip(","))
        lines.append("};")
        lines.append("")

    lines.extend(
        [
            "inline WiimoteTexture wiimoteTextureFor(WiimoteFaceTex face) {",
            "  switch (face) {",
            "    case WiimoteFaceTex::Front:",
            f"      return {{{TEXTURES[0][2]}, {TEXTURES[0][3]}, {TEXTURES[0][4]}}};",
            "    case WiimoteFaceTex::Back:",
            f"      return {{{TEXTURES[1][2]}, {TEXTURES[1][3]}, {TEXTURES[1][4]}}};",
            "    case WiimoteFaceTex::Top:",
            f"      return {{{TEXTURES[2][2]}, {TEXTURES[2][3]}, {TEXTURES[2][4]}}};",
            "    case WiimoteFaceTex::Bottom:",
            f"      return {{{TEXTURES[3][2]}, {TEXTURES[3][3]}, {TEXTURES[3][4]}}};",
            "    default:",
            "      return {nullptr, 0, 0};",
            "  }",
            "}",
            "",
        ]
    )

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
