#!/usr/bin/env python3
"""Emit wii_extension_regs.h from assets/wiimote_i2c.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
REPO_ROOT = PROJECT_DIR.parent.parent
JSON_PATH = REPO_ROOT / "assets" / "wiimote_i2c.json"
OUT_PATH = PROJECT_DIR / "include" / "wii_extension_regs.h"


def parse_hex_byte(value: str) -> int:
    return int(value, 16)


def emit_id(name: str, bytes_list: list[str]) -> list[str]:
    vals = ", ".join(f"0x{parse_hex_byte(b):02X}" for b in bytes_list)
    return [f"constexpr uint8_t kId{name}[6] = {{{vals}}};"]


def main() -> int:
    if not JSON_PATH.exists():
        print(f"Missing {JSON_PATH}", file=sys.stderr)
        return 1

    doc = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    bus = doc["bus"]
    ids = doc["extension_ids"]
    init = doc["initialization"]

    lines = [
        "#pragma once",
        "",
        "// Auto-generated by firmware/imu_demo/scripts/embed_wii_i2c.py",
        f"// Source: assets/wiimote_i2c.json ({doc.get('schema_name', '')} v{doc.get('schema_version', '')})",
        "",
        f"// Canonical Wiimote extension address (per spec): {bus['slave_address_7bit']}",
        f"constexpr uint8_t kExtSlaveAddrCanonical7bit = {bus['slave_address_7bit']};",
        f"constexpr uint8_t kExtSlaveAddr7bit = {bus.get('esp32_slave_address_7bit', bus['slave_address_7bit'])};",
        f"constexpr uint32_t kExtI2cSpeedHz = {bus['i2c_speed_hz']};",
        "constexpr uint16_t kRegBlockSize = 256;",
        "",
        "// Offsets within 0xA40000 / 0xA60000 virtual register blocks",
        "constexpr uint8_t kRegLiveDataOff = 0x08;",
        "constexpr uint8_t kRegInitOff = 0xF0;",
        "constexpr uint8_t kRegInitDoneOff = 0xFB;",
        "constexpr uint8_t kRegFormatOff = 0xFE;",
        "constexpr uint8_t kRegIdOff = 0xFA;",
        "",
        "constexpr uint8_t kInitDisableEncryption = 0x55;",
        "constexpr uint8_t kInitCompleteByte = 0x00;",
        "constexpr uint8_t kMpActivateOnly = 0x04;",
        "constexpr uint8_t kMpActivateNunchukPassthrough = 0x05;",
        "constexpr uint8_t kMpActivateClassicPassthrough = 0x07;",
        "",
        "constexpr uint8_t kLiveReportLen = 6;",
        "constexpr uint8_t kIdLen = 6;",
        "",
    ]

    id_map = {
        "Nunchuk": ids["nunchuk"]["id_bytes"],
        "Classic": ids["classic_controller"]["id_bytes"],
        "MpInactiveA6": ids["wii_motion_plus_inactive_at_motionplus_block"]["id_bytes"],
        "MpInactiveA4": ids["wii_motion_plus_inactive_at_standard_block"]["id_bytes"],
        "MpActive": ids["wii_motion_plus_active"]["id_bytes"],
        "MpNunchukPass": ids["wii_motion_plus_nunchuk_passthrough"]["id_bytes"],
        "MpClassicPass": ids["wii_motion_plus_classic_passthrough"]["id_bytes"],
    }
    for name, byte_list in id_map.items():
        lines.extend(emit_id(name, byte_list))
        lines.append("")

    lines.extend(
        [
            "struct IdLabel {",
            "  const uint8_t* bytes;",
            "  const char* label;",
            "};",
            "",
            "constexpr IdLabel kKnownIds[] = {",
        ]
    )
    for name, byte_list in id_map.items():
        lines.append(f'  {{kId{name}, "{name}"}},')
    lines.extend(["};", f"constexpr uint8_t kKnownIdCount = {len(id_map)};", ""])

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
